version: "3.7"

services:
  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      LOG_LEVEL: info
      MONGO_URL: mongodb://mongo:27017/test
volumes:
  data:
